//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SDBees.Core.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    using System.Runtime.Serialization;

    ///
	/// <remarks>Für dieses SDBees Plugin vorhandene Entities und Properties</remarks>
    /// 
    [DataContract]
	public class SDBeesExternalAvailableInfo
	{
        public SDBeesExternalAvailableInfo()
        {
            m_availableEntityInfos = null;
            m_pluginId = null;
            m_pluginRoleId = null;
        }

        public SDBeesExternalAvailableInfo(SDBeesPluginId pluginId, SDBeesPluginRoleId pluginRoleId, HashSet<SDBeesExternalEntityInfo> availableEntityInfos)
        {
            m_pluginId = pluginId;
            m_pluginRoleId = pluginRoleId;
            m_availableEntityInfos = availableEntityInfos;
        }

        private HashSet<SDBeesExternalEntityInfo> m_availableEntityInfos = null;
        /// <summary>
        /// im Plugin verfügbare Entities 
        /// </summary>
        [DataMember]
        public HashSet<SDBeesExternalEntityInfo> AvailableEntityInfos
		{
			get {return m_availableEntityInfos;}
			set {m_availableEntityInfos = value;}
		}

        private SDBeesPluginId m_pluginId;
        /// <summary>
        /// Id des Plugin
        /// </summary>
        [DataMember]
		public SDBeesPluginId PluginId
		{
			get { return m_pluginId; }
			set { m_pluginId = value; }
		}

        private SDBeesPluginRoleId m_pluginRoleId;
        /// <summary>
        /// Id der Plugin Rolle
        /// </summary>
        [DataMember]
        public SDBeesPluginRoleId PluginRoleId
        {
            get { return m_pluginRoleId; }
            set { m_pluginRoleId = value; }
        }

	}
}

