//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SDBees.Core.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    using System.Runtime.Serialization;

    /// <summary>
    /// Definition der Eigenschaft im Plugin
    /// </summary>
	[DataContract]
	public class SDBeesExternalPropertyInfo
	{
        public SDBeesExternalPropertyInfo()
        {
            m_name = null;
            m_readPropertyAccessInfo = null;
            m_mappingTypeNames = new List<string>();
        }

        //public SDBeesExternalPropertyInfo(string name, string propertyAccessInfo)
        //{
        //    m_name = new SDBeesLabel();
        //    m_readPropertyAccessInfo = propertyAccessInfo;
        //    m_writePropertyAccessInfo = propertyAccessInfo;
        //    m_mappingTypeNames = new List<string>();
        //}

        public SDBeesExternalPropertyInfo(string name, string readPropertyAccessInfo, string writePropertyAccessInfo)
        {
            m_name = new SDBeesLabel();
            m_readPropertyAccessInfo = readPropertyAccessInfo;
            m_writePropertyAccessInfo = writePropertyAccessInfo;
            m_mappingTypeNames = new List<string>();
        }

        private SDBeesLabel m_name;
        /// <summary>
        /// Der plugin Name der Eigenschaft 
        /// </summary>
        [DataMember]
        public SDBeesLabel Name
        {
            get { return m_name; }
            set { m_name = value; }
        }

        private string m_readPropertyAccessInfo;
        /// <summary>
        /// EigenschaftsInfo im Plugin
        /// </summary>
        [DataMember]
        public string ReadPropertyAccessInfo
        {
            get { return m_readPropertyAccessInfo; }
            set { m_readPropertyAccessInfo = value; }
        }

        private string m_writePropertyAccessInfo;
        /// <summary>
        /// EigenschaftsInfo im Plugin
        /// </summary>
        [DataMember]
        public string WritePropertyAccessInfo
        {
            get { return m_writePropertyAccessInfo; }
            set { m_writePropertyAccessInfo = value; }
        }

        //public string PropertyAccessInfo
        //{
        //    get { return m_readPropertyAccessInfo; }
        //    set { m_readPropertyAccessInfo = value; m_writePropertyAccessInfo = value; }
        //}

        private List<string> m_mappingTypeNames;
        [DataMember]
        public List<string> MappingTypeNames
        {
            get { return m_mappingTypeNames; }
            set { m_mappingTypeNames = value; }
        }
    }
}

