//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SDBees.Core.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    using System.Runtime.Serialization;

    /// <summary>
    /// Informationen die das Plugin SDBees zur Verfügung stellt
    /// </summary>
	[DataContract]
	public class SDBeesExternalEntityInfo
	{
        public SDBeesExternalEntityInfo()
        {
            m_name = new SDBeesLabel();
            m_availablePropertyInfos = new HashSet<SDBeesExternalPropertyInfo>();
            m_supportedSourceRelationships = new HashSet<SDBeesRelationshipDefinitionId>();
            m_supportedTargetRelationships = new HashSet<SDBeesRelationshipDefinitionId>();
        }

        public SDBeesExternalEntityInfo(string name, HashSet<SDBeesExternalPropertyInfo> propertyInfos, HashSet<SDBeesRelationshipDefinitionId> sourceRelationships, HashSet<SDBeesRelationshipDefinitionId> targetRelationships)
        {
            m_name = name;
            m_availablePropertyInfos = propertyInfos;
            m_supportedSourceRelationships = sourceRelationships;
            m_supportedTargetRelationships = targetRelationships;
        }

        private SDBeesLabel m_name;
        /// <summary>
        /// Der Plugin Name des Entites 
        /// </summary>
        [DataMember]
        public SDBeesLabel Name
        {
            get { return m_name; }
            set { m_name = value; }
        }

        private string m_entityAccessInfo;
        /// <summary>
        /// Entity Info im Plugin
        /// </summary>
        [DataMember]
        public string EntityAccessInfo
        {
            get { return m_entityAccessInfo; }
            set { m_entityAccessInfo = value; }
        }

		private HashSet<SDBeesExternalPropertyInfo> m_availablePropertyInfos;
        /// <summary>
        /// Verfügbare Eigenschaften des Entities im Plugin
        /// </summary>
        [DataMember]
		public HashSet<SDBeesExternalPropertyInfo> AvailablePropertyInfos
		{
            get { return m_availablePropertyInfos; }
            set { m_availablePropertyInfos = value; }
		}

        public HashSet<SDBeesRelationshipDefinitionId> m_supportedSourceRelationships;
        /// <summary>
        /// Verfügbare Quell Beziehungen
        /// </summary>
        [DataMember]
		public HashSet<SDBeesRelationshipDefinitionId> SupportedSourceRelationships
		{
            get { return m_supportedSourceRelationships; }
            set { m_supportedSourceRelationships = value; }
		}

		public HashSet<SDBeesRelationshipDefinitionId> m_supportedTargetRelationships;
        /// <summary>
        /// Verfügbare Ziel Beziehungen
        /// </summary>
        [DataMember]
		public HashSet<SDBeesRelationshipDefinitionId> SupportedTargetRelationships
		{
            get { return m_supportedTargetRelationships; }
            set { m_supportedTargetRelationships = value; }
		}

	}
}

