//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SDBees.Core.Model
{
    /// <summary>
    /// SDBees Plugin abhängige Definitionen
    /// </summary>
    [DataContract]
	public class SDBeesExternalMappings
	{
        public SDBeesExternalMappings()
        {
            m_id = new SDBeesPluginId();
            m_pluginRole = new SDBeesPluginRoleId();
            m_entityMappings = new HashSet<SDBeesMappedEntityDefinition>();
            m_mappingTypes = new List<string>();
        }

        public SDBeesExternalMappings(SDBeesPluginId pluginId, SDBeesPluginRoleId roleId, HashSet<SDBeesMappedEntityDefinition> mappings)
        {
            m_id = pluginId;
            m_pluginRole = roleId;
            m_entityMappings = mappings;
            m_mappingTypes = new List<string>();
        }

        private SDBeesPluginId m_id;
        /// <summary>
        /// Id des Plugins
        /// </summary>
        [DataMember]
        public SDBeesPluginId PluginId
        {
            get { return m_id; }
            set { m_id = value; }
        }

        private SDBeesPluginRoleId m_pluginRole;
        /// <summary>
        /// Gewerk, Rolle des Plugins
        /// </summary>
        [DataMember]
        public SDBeesPluginRoleId RoleId
        {
            get { return m_pluginRole; }
            set { m_pluginRole = value; }
        }

        private HashSet<SDBeesMappedEntityDefinition> m_entityMappings = new HashSet<SDBeesMappedEntityDefinition>();
        /// <summary>
        /// Alle gemappten Entities mit jeweils allen gemappten Attributen und Beziehungen
        /// </summary>
        [DataMember]
		public HashSet<SDBeesMappedEntityDefinition> EntityMappings
		{
            get { return m_entityMappings; }
            set { m_entityMappings = value; }
		}

        private List<string> m_mappingTypes = new List<string>();
        [DataMember]
        public List<string> MappingTypes
        {
            get { return m_mappingTypes; }
            set { m_mappingTypes = value; }
        }
    }
}

