//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace SDBees.Core.Model
{
    /// <summary>
    /// Mapping für eine Eigenschaft eines Entities
    /// </summary>
	[DataContract]
	public class SDBeesMappedPropertyDefinition
	{
        public SDBeesMappedPropertyDefinition()
        {
            m_pluginPropertyInfo = new SDBeesExternalPropertyInfo();
            m_propertyDefinitionId = new SDBeesPropertyDefinitionId();
            m_editable = true;
        }

        public SDBeesMappedPropertyDefinition(SDBeesPropertyDefinitionId definitionId, SDBeesExternalPropertyInfo externalPropertyInfo)
        {
            m_pluginPropertyInfo = externalPropertyInfo;
            m_propertyDefinitionId = definitionId;
            m_editable = true;
        }

		private SDBeesExternalPropertyInfo m_pluginPropertyInfo;
        /// <summary>
        /// Die gemappte Eigenschaft im Plugin
        /// </summary>
        [DataMember]
		public SDBeesExternalPropertyInfo PluginPropertyInfo
		{
            get { return m_pluginPropertyInfo; }
            set { m_pluginPropertyInfo = value; }
		}

		private SDBeesPropertyDefinitionId m_propertyDefinitionId;
        /// <summary>
        /// Die Eigenschafts Definition im SDBees
        /// </summary>
        [DataMember]
		public SDBeesPropertyDefinitionId PropertyDefinitionId
		{
            get { return m_propertyDefinitionId; }
            set { m_propertyDefinitionId = value; }
		}

        private bool m_editable;
        /// <summary>
        /// Editierbar?
        /// </summary>
        [DataMember]
        public bool Editable
        {
            get { return m_editable; }
            set { m_editable = value; }
        }
	}
}

